services:
  react-todo-app:
    image: react-app
    build: .
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  # node-web-api:
  #   image: node-web-api
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - mern-app

networks:
  mern-app:
    driver: bridge